tosca_definitions_version: tosca_simple_yaml_1_3
relationship_types:
  basicrelationship:
    derived_from: tosca.relationships.Root
topology_template:
  node_templates:
    Knowledge Base:
      type: tosca.nodes.SoftwareComponent
      description: Stores knowledge related to the AN.
      requirements:
      - export:
          node: Knowledge Base
          relationship: exports
      - import:
          node: Knowledge Base
          relationship: imports
    Knowledge Base Manager:
      type: tosca.nodes.SoftwareComponent
      requirements:
      - export:
          node: Knowledge Base
          relationship: exports
      - optimize:
          node: Knowledge Base
          relationship: optimizes
    AN Orchestrator:
      type: tosca.nodes.Compute
      requirements:
      - refer:
          node: Knowledge Base
          relationship: refersTo
      - generates_Tosca:
          node: Auto controller generator
          relationship: generates
    Auto controller generator:
      type: tosca.nodes.SoftwareComponent
      description: Generate controller specifications
      requirements:
      - dependency: ML Pipeline
    OpenCN:
      type: tosca.nodes.SoftwareComponent
      description: Stores controllers
    ML Pipeline:
      type: tosca.nodes.SoftwareComponent
      description: Hosts analytics
    Human operator:
      type: tosca.nodes.SoftwareComponent
      description: Reads reports and monitors
  relationship_templates:
    refersTo:
      type: basicrelationship
    optimizes:
      type: basicrelationship
    exports:
      type: basicrelationship
    stores:
      type: basicrelationship
    recommends:
      type: basicrelationship
    imports:
      type: basicrelationship
    reads:
      type: basicrelationship
    monitors:
      type: basicrelationship
    inputs:
      type: basicrelationship
    generates:
      type: basicrelationship
